=== ShadySentry/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="fullName"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="email"/>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="Project" type="projectType"/>

    <xs:complexType name="projectType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
                <xs:attribute type="xs:string" name="description" use="optional"/>
                <xs:attribute type="groupType" name="groupType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

<!--    <xs:element name="Group" type="groupType"/>-->

    <xs:simpleType name="groupType">
            <xs:restriction base="xs:string">
                <xs:enumeration value="REGISTERING"/>
                <xs:enumeration value="CURRENT"/>
                <xs:enumeration value="FINISHED"/>
            </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ShadySentry/masterjava/src/main/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Projects>
        <Project name="topjava">
            <description>TopJava project</description>
            <Group name="topjava08" type="REGISTERING"/>
            <Group name="topjava09" type="REGISTERING"/>
            <Group name="topjava10" type="REGISTERING"/>

        </Project>
        <Project name="masterJava">
            <description>MasterJava project</description>
            <Group name="masterJava21" type="CURRENT"/>
        </Project>
    </Projects>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Full Name</fullName>
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru" groupRefs="topjava08 topjava10 masterJava21">
<!--            <email>admin@javaops.ru</email>-->
            <fullName>Admin</fullName>
        </User>
        <User flag="active" email="asdasd@DF.com" city="spb" groupRefs="masterJava21">
            <fullName>rnd user</fullName>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">
<!--            <email>mail@yandex.ru</email>-->
            <fullName>Deleted</fullName>
        </User>
    </Users>
</Payload>

=== ShadySentry/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Full Name</fullName>
            <project>masterjava</project>
        </User>
        <User flag="superuser" city="spb" email="admin@javaops.ru">
<!--            <email>admin@javaops.ru</email>-->
            <fullName>Admin</fullName>
            <project>masterjava</project>
            <project>topjava20</project>
            <project>topjava19</project>
        </User>
        <User flag="deleted" city="spb" email="mail@yandex.ru">
<!--            <email>mail@yandex.ru</email>-->
            <fullName>Deleted</fullName>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project id="masterjava" description="masterjava project" groupType="CURRENT">masterjava</Project>
        <Project id="topjava19" description="topjava 19 project" groupType="FINISHED">masterjava</Project>
        <Project id="topjava20" description="topjava 21 project" groupType="REGISTERING">masterjava</Project>
    </Projects>
</Payload>
